# Create performance test results
TOPDIR=../..
# global.mk recursively includes all .mk files in the project
# including the ones in the current directory.
include $(TOPDIR)/global.mk

default: python3_idiomatic1_default
